Repository Ureca-Dangdang-salon/dang_server, pull requests merged in 2024-11, with the labels that each got.

#5 feat: 엔티티 생성
  src/main/java/com/dangdangsalon/domain/chat/entity/ChatMessage.java
  src/main/java/com/dangdangsalon/domain/chat/entity/ChatRoom.java
  src/main/java/com/dangdangsalon/domain/chat/entity/SendRole.java
  src/main/java/com/dangdangsalon/domain/contest/entity/Contest.java
  src/main/java/com/dangdangsalon/domain/contest/entity/ContestPost.java
  src/main/java/com/dangdangsalon/domain/coupon/entity/Coupon.java
  src/main/java/com/dangdangsalon/domain/coupon/entity/CouponEvent.java
  src/main/java/com/dangdangsalon/domain/coupon/entity/CouponEventStatus.java
  src/main/java/com/dangdangsalon/domain/coupon/entity/CouponStatus.java
  src/main/java/com/dangdangsalon/domain/coupon/entity/DiscountType.java
  src/main/java/com/dangdangsalon/domain/dogprofile/entity/DogProfile.java
  src/main/java/com/dangdangsalon/domain/dogprofile/entity/DogProfileFeature.java
  src/main/java/com/dangdangsalon/domain/dogprofile/entity/Gender.java
  src/main/java/com/dangdangsalon/domain/dogprofile/entity/Neutering.java
  src/main/java/com/dangdangsalon/domain/estimate/entity/Estimate.java
  src/main/java/com/dangdangsalon/domain/estimate/entity/EstimatePicture.java
  src/main/java/com/dangdangsalon/domain/estimate/entity/EstimateServicePrice.java
  src/main/java/com/dangdangsalon/domain/estimate/entity/EstimateStatus.java
  src/main/java/com/dangdangsalon/domain/estimaterequest/entity/EstimateRequest.java
  src/main/java/com/dangdangsalon/domain/estimaterequest/entity/EstimateRequestService.java
  src/main/java/com/dangdangsalon/domain/estimaterequest/entity/RequestStatus.java
  src/main/java/com/dangdangsalon/domain/feature/entity/Feature.java
  src/main/java/com/dangdangsalon/domain/groomerprofile/entity/Badge.java
  src/main/java/com/dangdangsalon/domain/groomerprofile/entity/GroomerBadge.java
  src/main/java/com/dangdangsalon/domain/groomerprofile/entity/GroomerProfile.java
  src/main/java/com/dangdangsalon/domain/groomerprofile/entity/GroomerProfileService.java
  src/main/java/com/dangdangsalon/domain/groomerprofile/entity/ServiceType.java
  src/main/java/com/dangdangsalon/domain/groomerservice/entity/GroomerService.java
  src/main/java/com/dangdangsalon/domain/notification/entity/Notification.java
  src/main/java/com/dangdangsalon/domain/notification/entity/NotificationStatus.java
  src/main/java/com/dangdangsalon/domain/orders/entity/OrderStatus.java
  src/main/java/com/dangdangsalon/domain/orders/entity/Orders.java
  src/main/java/com/dangdangsalon/domain/payment/entity/Payment.java
  src/main/java/com/dangdangsalon/domain/payment/entity/PaymentStatus.java
  src/main/java/com/dangdangsalon/domain/region/entity/City.java
  src/main/java/com/dangdangsalon/domain/region/entity/District.java
  src/main/java/com/dangdangsalon/domain/region/entity/DistrictService.java
  src/main/java/com/dangdangsalon/domain/review/entity/Review.java
  src/main/java/com/dangdangsalon/domain/user/entity/Role.java
  src/main/java/com/dangdangsalon/domain/user/entity/User.java
Labels: ✨ Feat

#7 Feature: Loki 세팅 추가
  src/main/resources/application-prod.properties
Labels: ✨ Feat

#8 Refactor: 엔티티 수정
  src/main/java/com/dangdangsalon/domain/estimate/entity/Estimate.java
  src/main/java/com/dangdangsalon/domain/estimate/request/entity/EstimateRequest.java
  src/main/java/com/dangdangsalon/domain/estimate/request/entity/EstimateRequestProfiles.java
  src/main/java/com/dangdangsalon/domain/groomerprofile/review/entity/Review.java
  src/main/java/com/dangdangsalon/domain/groomerprofile/review/entity/ReviewImage.java
  src/main/resources/db/migration/V2__Add_review_Image.sql
  src/main/resources/db/migration/V3__Add_estimate_request.sql
Labels: 🚀 Refactor

#10 Refactor: 엔티티 수정
  src/main/java/com/dangdangsalon/domain/groomerprofile/request/entity/GroomerEstimateRequest.java
  src/main/java/com/dangdangsalon/domain/groomerprofile/request/entity/GroomerRequestStatus.java
  src/main/resources/db/migration/V4__Add_groomer_request.sql
Labels: 🚀 Refactor

#12 Refactor: 미용사 자격증 엔티티 추가 및 Flyway V4 적용
  src/main/java/com/dangdangsalon/domain/groomerprofile/entity/GroomerCertification.java
  src/main/java/com/dangdangsalon/domain/groomerprofile/entity/GroomerDetails.java
  src/main/resources/db/migration/V4__Add_groomer_request.sql
Labels: 🚀 Refactor

#19 Feat: CORS 설정을 위한 Config 클래스 생성
  build.gradle
  src/main/java/com/dangdangsalon/config/SecurityConfig.java
  src/main/java/com/dangdangsalon/config/WebConfig.java
Labels: ✨ Feat

#17 Feature: 견적 요청 등록, 반려견 조회 기능 구현
  src/main/java/com/dangdangsalon/domain/dogprofile/controller/DogProfileController.java
  src/main/java/com/dangdangsalon/domain/dogprofile/dto/DogProfileResponseDto.java
  src/main/java/com/dangdangsalon/domain/dogprofile/repository/DogProfileFeatureRepository.java
  src/main/java/com/dangdangsalon/domain/dogprofile/repository/DogProfileRepository.java
  src/main/java/com/dangdangsalon/domain/dogprofile/service/DogProfileService.java
  src/main/java/com/dangdangsalon/domain/estimate/request/controller/EstimateRequestController.java
  src/main/java/com/dangdangsalon/domain/estimate/request/dto/DogEstimateRequestDto.java
  src/main/java/com/dangdangsalon/domain/estimate/request/dto/EstimateDetailResponseDto.java
  src/main/java/com/dangdangsalon/domain/estimate/request/dto/EstimateRequestDto.java
  src/main/java/com/dangdangsalon/domain/estimate/request/dto/EstimateResponseDto.java
  src/main/java/com/dangdangsalon/domain/estimate/request/dto/FeatureResponseDto.java
  src/main/java/com/dangdangsalon/domain/estimate/request/dto/ServiceResponseDto.java
  src/main/java/com/dangdangsalon/domain/estimate/request/entity/EstimateRequest.java
  src/main/java/com/dangdangsalon/domain/estimate/request/repository/EstimateRequestProfilesRepository.java
  src/main/java/com/dangdangsalon/domain/estimate/request/repository/EstimateRequestRepository.java
  src/main/java/com/dangdangsalon/domain/estimate/request/repository/EstimateRequestServiceRepository.java
  src/main/java/com/dangdangsalon/domain/estimate/request/service/EstimateRequestDetailService.java
  src/main/java/com/dangdangsalon/domain/estimate/request/service/EstimateRequestInsertService.java
  src/main/java/com/dangdangsalon/domain/estimate/request/service/EstimateRequestServices.java
  src/main/java/com/dangdangsalon/domain/estimate/request/service/GroomerEstimateRequestService.java
  src/main/java/com/dangdangsalon/domain/groomerprofile/repository/GroomerCanServiceRepository.java
  src/main/java/com/dangdangsalon/domain/groomerprofile/repository/GroomerServiceAreaRepository.java
  src/main/java/com/dangdangsalon/domain/groomerprofile/request/entity/GroomerEstimateRequest.java
  src/main/java/com/dangdangsalon/domain/groomerprofile/request/repository/GroomerEstimateRequestRepository.java
  src/main/java/com/dangdangsalon/domain/groomerservice/repository/GroomerServiceRepository.java
  src/main/java/com/dangdangsalon/domain/region/repository/DistrictRepository.java
  src/main/java/com/dangdangsalon/domain/user/repository/UserRepository.java
  src/main/resources/db/migration/V4__Add_groomer_request.sql
Labels: 🎶 wontfix

#24 Feat: 네이버, 구글, 카카오 소셜로그인 구현
  src/main/java/com/dangdangsalon/config/RedisConfig.java
  src/main/java/com/dangdangsalon/config/SecurityConfig.java
  src/main/java/com/dangdangsalon/domain/auth/Social.java
  src/main/java/com/dangdangsalon/domain/auth/controller/AuthController.java
  src/main/java/com/dangdangsalon/domain/auth/dto/CustomOAuth2User.java
  src/main/java/com/dangdangsalon/domain/auth/dto/GoogleResponse.java
  src/main/java/com/dangdangsalon/domain/auth/dto/JoinAdditionalInfoDto.java
  src/main/java/com/dangdangsalon/domain/auth/dto/KakaoResponse.java
  src/main/java/com/dangdangsalon/domain/auth/dto/NaverResponse.java
  src/main/java/com/dangdangsalon/domain/auth/dto/OAuth2Response.java
  src/main/java/com/dangdangsalon/domain/auth/dto/UserDto.java
  src/main/java/com/dangdangsalon/domain/auth/handler/CustomSuccessHandler.java
  src/main/java/com/dangdangsalon/domain/auth/service/AuthService.java
  src/main/java/com/dangdangsalon/domain/auth/service/CustomOAuth2UserService.java
  src/main/java/com/dangdangsalon/domain/user/entity/Role.java
  src/main/java/com/dangdangsalon/domain/user/entity/User.java
  src/main/java/com/dangdangsalon/domain/user/repository/UserRepository.java
  src/main/java/com/dangdangsalon/exception/TokenExpiredException.java
  src/main/java/com/dangdangsalon/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/dangdangsalon/filter/JwtFilter.java
  src/main/java/com/dangdangsalon/util/CookieUtil.java
  src/main/java/com/dangdangsalon/util/JwtUtil.java
  src/main/java/com/dangdangsalon/util/RedisUtil.java
  src/main/resources/application-prod.properties
  src/main/resources/db/migration/V1__initial_schema.sql
Labels: help wanted, ✨ Feat

#32 Feat: 사용자 입장 견적서 API
  src/main/java/com/dangdangsalon/domain/estimate/controller/EstimateController.java
  src/main/java/com/dangdangsalon/domain/estimate/dto/MyEstimateDetailResponseDto.java
  src/main/java/com/dangdangsalon/domain/estimate/dto/MyEstimateResponseDto.java
  src/main/java/com/dangdangsalon/domain/estimate/repository/EstimateRepository.java
  src/main/java/com/dangdangsalon/domain/estimate/request/controller/EstimateRequestController.java
  src/main/java/com/dangdangsalon/domain/estimate/request/dto/DogNameResponseDto.java
  src/main/java/com/dangdangsalon/domain/estimate/request/dto/MyEstimateRequestDetailResponseDto.java
  src/main/java/com/dangdangsalon/domain/estimate/request/dto/MyEstimateRequestResponseDto.java
  src/main/java/com/dangdangsalon/domain/estimate/request/entity/EstimateRequest.java
  src/main/java/com/dangdangsalon/domain/estimate/request/repository/EstimateRequestProfilesRepository.java
  src/main/java/com/dangdangsalon/domain/estimate/request/repository/EstimateRequestRepository.java
  src/main/java/com/dangdangsalon/domain/estimate/request/service/EstimateRequestDetailService.java
  src/main/java/com/dangdangsalon/domain/estimate/request/service/EstimateRequestInsertService.java
  src/main/java/com/dangdangsalon/domain/estimate/request/service/EstimateRequestServices.java
  src/main/java/com/dangdangsalon/domain/estimate/request/service/GroomerEstimateRequestService.java
  src/main/java/com/dangdangsalon/domain/estimate/service/EstimateService.java
Labels: 🎶 wontfix, ✨ Feat

#35 Test: 콘테스트 API 테스트 코드 작성
  .gitignore
  build.gradle
  src/main/java/com/dangdangsalon/domain/contest/entity/ContestPost.java
  src/main/java/com/dangdangsalon/domain/contest/repository/ContestPostRepository.java
  src/main/java/com/dangdangsalon/domain/contest/service/ContestPostLikeService.java
  src/main/java/com/dangdangsalon/domain/contest/service/ContestService.java
  src/main/java/com/dangdangsalon/domain/user/entity/User.java
  src/main/resources/db/migration/V1__initial_schema.sql
  src/main/resources/db/migration/V2__Add_review_Image.sql
  src/main/resources/db/migration/V3__Add_estimate_request.sql
  src/main/resources/db/migration/V4__Add_groomer_request.sql
  src/main/resources/db/migration/V5__add_post_like.sql
  src/test/java/com/dangdangsalon/domain/auth/controller/AuthControllerTest.java
  src/test/java/com/dangdangsalon/domain/contest/api/ContestApiTest.java
  src/test/java/com/dangdangsalon/domain/contest/controller/ContestControllerTest.java
  src/test/java/com/dangdangsalon/domain/contest/controller/ContestPostControllerTest.java
  src/test/java/com/dangdangsalon/domain/contest/repository/ContestPostLikeRepositoryTest.java
  src/test/java/com/dangdangsalon/domain/contest/repository/ContestPostRepositoryTest.java
  src/test/java/com/dangdangsalon/domain/contest/repository/ContestRepositoryTest.java
  src/test/java/com/dangdangsalon/domain/contest/service/ContestPostLikeServiceTest.java
  src/test/java/com/dangdangsalon/domain/contest/service/ContestPostServiceTest.java
  src/test/java/com/dangdangsalon/domain/contest/service/ContestServiceTest.java
  src/test/resources/application-test.properties
Labels: 🎶 wontfix, 📰 Test

#39 Feat: 주문 등록, 결제 승인, 결제 취소, 내 정보 결제 내역 조회 기능 구현
  build.gradle
  src/main/java/com/dangdangsalon/config/WebClientConfig.java
  src/main/java/com/dangdangsalon/domain/estimate/request/repository/EstimateRequestServiceRepository.java
  src/main/java/com/dangdangsalon/domain/orders/controller/OrdersController.java
  src/main/java/com/dangdangsalon/domain/orders/dto/OrdersRequestDto.java
  src/main/java/com/dangdangsalon/domain/orders/dto/OrdersResponseDto.java
  src/main/java/com/dangdangsalon/domain/orders/entity/OrderStatus.java
  src/main/java/com/dangdangsalon/domain/orders/entity/Orders.java
  src/main/java/com/dangdangsalon/domain/orders/repository/OrdersRepository.java
  src/main/java/com/dangdangsalon/domain/orders/service/OrdersService.java
  src/main/java/com/dangdangsalon/domain/payment/controller/PaymentController.java
  src/main/java/com/dangdangsalon/domain/payment/dto/PaymentApproveRequestDto.java
  src/main/java/com/dangdangsalon/domain/payment/dto/PaymentApproveResponseDto.java
  src/main/java/com/dangdangsalon/domain/payment/dto/PaymentCancelRequestDto.java
  src/main/java/com/dangdangsalon/domain/payment/dto/PaymentCancelResponseDto.java
  src/main/java/com/dangdangsalon/domain/payment/dto/PaymentDogProfileResponseDto.java
  src/main/java/com/dangdangsalon/domain/payment/dto/PaymentResponseDto.java
  src/main/java/com/dangdangsalon/domain/payment/entity/Payment.java
  src/main/java/com/dangdangsalon/domain/payment/repository/PaymentRepository.java
  src/main/java/com/dangdangsalon/domain/payment/service/PaymentGetService.java
  src/main/java/com/dangdangsalon/domain/payment/service/PaymentService.java
  src/main/resources/db/migration/V6__ADD_orders_column.sql
Labels: 🎶 wontfix, ✨ Feat

#36 Test: 견적서 API 테스트 코드 작성
  src/main/java/com/dangdangsalon/domain/dogprofile/dto/DogProfileResponseDto.java
  src/main/java/com/dangdangsalon/domain/dogprofile/entity/DogAge.java
  src/main/java/com/dangdangsalon/domain/estimate/controller/EstimateController.java
  src/main/java/com/dangdangsalon/domain/estimate/dto/DogPriceRequestDto.java
  src/main/java/com/dangdangsalon/domain/estimate/dto/EstimateIdResponseDto.java
  src/main/java/com/dangdangsalon/domain/estimate/dto/EstimateWriteRequestDto.java
  src/main/java/com/dangdangsalon/domain/estimate/dto/ServiceRequestDto.java
  src/main/java/com/dangdangsalon/domain/estimate/service/EstimateService.java
  src/test/java/com/dangdangsalon/domain/dogprofile/controller/DogProfileControllerTest.java
  src/test/java/com/dangdangsalon/domain/dogprofile/repository/DogProfileRepositoryTest.java
  src/test/java/com/dangdangsalon/domain/dogprofile/service/DogProfileServiceTest.java
  src/test/java/com/dangdangsalon/domain/estimate/api/EstimateApiTest.java
  src/test/java/com/dangdangsalon/domain/estimate/controller/EstimateControllerTest.java
  src/test/java/com/dangdangsalon/domain/estimate/repository/EstimateRepositoryTest.java
  src/test/java/com/dangdangsalon/domain/estimate/request/api/EstimateRequestApiTest.java
  src/test/java/com/dangdangsalon/domain/estimate/request/controller/EstimateRequestControllerTest.java
  src/test/java/com/dangdangsalon/domain/estimate/request/repository/EstimateRequestProfilesRepositoryTest.java
  src/test/java/com/dangdangsalon/domain/estimate/request/repository/EstimateRequestRepositoryTest.java
  src/test/java/com/dangdangsalon/domain/estimate/request/repository/EstimateRequestServiceRepositoryTest.java
  src/test/java/com/dangdangsalon/domain/estimate/request/service/EstimateRequestDetailServiceTest.java
  src/test/java/com/dangdangsalon/domain/estimate/request/service/EstimateRequestInsertServiceTest.java
  src/test/java/com/dangdangsalon/domain/estimate/request/service/EstimateRequestServicesTest.java
  src/test/java/com/dangdangsalon/domain/estimate/request/service/GroomerEstimateRequestServiceTest.java
  src/test/java/com/dangdangsalon/domain/estimate/service/EstimateServiceTest.java
  src/test/java/com/dangdangsalon/domain/estimate/service/EstimateWriteServiceTest.java
  src/test/java/com/dangdangsalon/domain/groomerprofile/repository/GroomerCanServiceRepositoryTest.java
  src/test/java/com/dangdangsalon/domain/groomerprofile/repository/GroomerProfileRepositoryTest.java
  src/test/java/com/dangdangsalon/domain/groomerprofile/repository/GroomerServiceAreaRepositoryTest.java
  src/test/java/com/dangdangsalon/domain/groomerservice/repository/GroomerServiceRepositoryTest.java
Labels: 🎶 wontfix, 📰 Test

#45 Refactor: 결제 내역 조회 미용사 이름 및 사진 추가
  src/main/java/com/dangdangsalon/domain/estimate/request/controller/EstimateRequestController.java
  src/main/java/com/dangdangsalon/domain/estimate/request/service/GroomerEstimateRequestService.java
  src/main/java/com/dangdangsalon/domain/payment/dto/PaymentResponseDto.java
  src/main/java/com/dangdangsalon/domain/payment/service/PaymentGetService.java
  src/test/java/com/dangdangsalon/domain/estimate/request/api/EstimateRequestApiTest.java
  src/test/java/com/dangdangsalon/domain/estimate/request/controller/EstimateRequestControllerTest.java
  src/test/java/com/dangdangsalon/domain/estimate/request/service/GroomerEstimateRequestServiceTest.java
  src/test/java/com/dangdangsalon/domain/payment/service/PaymentGetServiceTest.java
Labels: 🎶 wontfix, 🚀 Refactor

#53 Refactor: name 컬럼 추가
  src/main/java/com/dangdangsalon/domain/mypage/dto/res/CommonProfileResponseDto.java
  src/test/java/com/dangdangsalon/domain/mypage/controller/MyPageCommonControllerTest.java
Labels: 🎶 wontfix
