Repository Ureca-Dangdang-salon/dang_server, pull requests merged in 2024-12, with the labels that each got.

#52 Refactor: 견적 요청 등록에 1대1 요청 등록 로직 추가
  src/main/java/com/dangdangsalon/domain/estimate/request/dto/EstimateRequestDto.java
  src/main/java/com/dangdangsalon/domain/estimate/request/service/EstimateRequestServices.java
  src/main/java/com/dangdangsalon/domain/estimate/request/service/GroomerEstimateRequestService.java
  src/main/java/com/dangdangsalon/domain/region/repository/DistrictRepository.java
  src/test/java/com/dangdangsalon/domain/estimate/request/controller/EstimateRequestControllerTest.java
  src/test/java/com/dangdangsalon/domain/estimate/request/service/EstimateRequestInsertServiceTest.java
  src/test/java/com/dangdangsalon/domain/estimate/request/service/EstimateRequestServicesTest.java
  src/test/java/com/dangdangsalon/domain/estimate/request/service/GroomerEstimateRequestServiceTest.java
Labels: 🎶 wontfix, 🚀 Refactor

#55 Chore: 마이페이지 사용자 조회 api url 변경
  src/main/java/com/dangdangsalon/domain/mypage/controller/MyPageDogProfileController.java
  src/test/java/com/dangdangsalon/domain/mypage/api/MyPageApiTest.java
  src/test/java/com/dangdangsalon/domain/mypage/controller/MyPageDogProfileControllerTest.java
Labels: 🎶 wontfix

#59 Refactor: 미용사 프로필 조회 제공 서비스 isCustom 제거
  src/main/java/com/dangdangsalon/domain/groomerprofile/repository/GroomerProfileRepository.java
  src/main/java/com/dangdangsalon/domain/mypage/dto/res/GroomerProfileDetailsInfoResponseDto.java
  src/main/java/com/dangdangsalon/domain/mypage/dto/res/GroomerServicesResponseDto.java
  src/main/java/com/dangdangsalon/domain/mypage/service/MyPageGroomerService.java
  src/test/java/com/dangdangsalon/domain/groomerprofile/repository/GroomerProfileRepositoryTest.java
  src/test/java/com/dangdangsalon/domain/mypage/service/MyPageGroomerServiceTest.java
Labels: 🚀 Refactor

#51 Feature: 알림 기능 구현 (FCM, 이메일)
  build.gradle
  src/main/java/com/dangdangsalon/domain/estimate/controller/EstimateController.java
  src/main/java/com/dangdangsalon/domain/estimate/entity/Estimate.java
  src/main/java/com/dangdangsalon/domain/estimate/repository/EstimateRepository.java
  src/main/java/com/dangdangsalon/domain/estimate/request/service/GroomerEstimateRequestNotificationService.java
  src/main/java/com/dangdangsalon/domain/estimate/request/service/GroomerEstimateRequestService.java
  src/main/java/com/dangdangsalon/domain/estimate/service/EstimateNotificationService.java
  src/main/java/com/dangdangsalon/domain/estimate/service/EstimateService.java
  src/main/java/com/dangdangsalon/domain/notification/controller/NotificationController.java
  src/main/java/com/dangdangsalon/domain/notification/dto/FcmTokenRequestDto.java
  src/main/java/com/dangdangsalon/domain/notification/dto/FcmTokenTopicRequestDto.java
  src/main/java/com/dangdangsalon/domain/notification/dto/NotificationDto.java
  src/main/java/com/dangdangsalon/domain/notification/dto/ReviewNotificationDto.java
  src/main/java/com/dangdangsalon/domain/notification/entity/FcmToken.java
  src/main/java/com/dangdangsalon/domain/notification/entity/Notification.java
  src/main/java/com/dangdangsalon/domain/notification/entity/NotificationStatus.java
  src/main/java/com/dangdangsalon/domain/notification/initializer/FCMInitializer.java
  src/main/java/com/dangdangsalon/domain/notification/repository/FcmTokenRepository.java
  src/main/java/com/dangdangsalon/domain/notification/service/NotificationEmailService.java
  src/main/java/com/dangdangsalon/domain/notification/service/NotificationScheduler.java
  src/main/java/com/dangdangsalon/domain/notification/service/NotificationService.java
  src/main/java/com/dangdangsalon/domain/notification/service/NotificationTopicService.java
  src/main/java/com/dangdangsalon/domain/notification/service/RedisNotificationService.java
  src/main/java/com/dangdangsalon/domain/orders/service/OrdersService.java
  src/main/java/com/dangdangsalon/domain/payment/controller/PaymentController.java
  src/main/java/com/dangdangsalon/domain/payment/dto/PaymentApproveResponseDto.java
  src/main/java/com/dangdangsalon/domain/payment/dto/PaymentCancelResponseDto.java
  src/main/java/com/dangdangsalon/domain/payment/dto/PaymentDogProfileResponseDto.java
  src/main/java/com/dangdangsalon/domain/payment/dto/PaymentResponseDto.java
  src/main/java/com/dangdangsalon/domain/payment/service/PaymentNotificationService.java
  src/main/java/com/dangdangsalon/domain/payment/service/PaymentService.java
  src/main/java/com/dangdangsalon/domain/user/entity/User.java
  src/main/resources/db/migration/V9__add_fcm_token.sql
Labels: 🎶 wontfix, ✨ Feat

#63 Refactor: 견적서 수정(미용사), 견적서 거절하기(사용자) 추가
  src/main/java/com/dangdangsalon/domain/estimate/controller/EstimateController.java
  src/main/java/com/dangdangsalon/domain/estimate/dto/EstimateResponseDto.java
  src/main/java/com/dangdangsalon/domain/estimate/dto/EstimateUpdateRequestDto.java
  src/main/java/com/dangdangsalon/domain/estimate/entity/Estimate.java
  src/main/java/com/dangdangsalon/domain/estimate/repository/EstimateRepository.java
  src/main/java/com/dangdangsalon/domain/estimate/request/dto/EstimateRequestResponseDto.java
  src/main/java/com/dangdangsalon/domain/estimate/request/service/GroomerEstimateRequestService.java
  src/main/java/com/dangdangsalon/domain/estimate/service/EstimateService.java
  src/main/java/com/dangdangsalon/domain/estimate/service/EstimateUpdateService.java
Labels: 🎶 wontfix, 🚀 Refactor

#67 Refactor: 지역 id 및 미용사 프로필 등록 필수, 선택 필드 변경
  src/main/java/com/dangdangsalon/domain/groomerprofile/entity/GroomerProfile.java
  src/main/java/com/dangdangsalon/domain/groomerprofile/repository/GroomerProfileRepository.java
  src/main/java/com/dangdangsalon/domain/mypage/controller/MyPageGroomerController.java
  src/main/java/com/dangdangsalon/domain/mypage/dto/req/GroomerProfileDetailsRequestDto.java
  src/main/java/com/dangdangsalon/domain/mypage/dto/req/GroomerProfileRequestDto.java
  src/main/java/com/dangdangsalon/domain/mypage/dto/res/CommonProfileResponseDto.java
  src/main/java/com/dangdangsalon/domain/mypage/dto/res/DistrictResponseDto.java
  src/main/java/com/dangdangsalon/domain/mypage/dto/res/UserProfileResponseDto.java
  src/main/java/com/dangdangsalon/domain/mypage/service/MyPageGroomerService.java
  src/test/java/com/dangdangsalon/domain/mypage/api/MyPageApiTest.java
  src/test/java/com/dangdangsalon/domain/mypage/controller/MyPageCommonControllerTest.java
  src/test/java/com/dangdangsalon/domain/mypage/controller/MyPageGroomerControllerTest.java
  src/test/java/com/dangdangsalon/domain/mypage/service/MyPageGroomerServiceTest.java
Labels: 🚀 Refactor

#65 Refactor: FCM 시크릿 키 json 에서 환경 변수로 변경
  src/main/java/com/dangdangsalon/domain/notification/initializer/FCMInitializer.java
Labels: 🎶 wontfix, 🚀 Refactor

#73 Refactor: 견적서 보내기(미용사) 예약 날짜 저장 로직 변경, 결제 내역 조회 예약일 추가
  src/main/java/com/dangdangsalon/domain/estimate/dto/EstimateWriteRequestDto.java
  src/main/java/com/dangdangsalon/domain/estimate/service/EstimateService.java
  src/main/java/com/dangdangsalon/domain/payment/dto/PaymentResponseDto.java
  src/main/java/com/dangdangsalon/domain/payment/service/PaymentGetService.java
  src/test/java/com/dangdangsalon/domain/estimate/api/EstimateApiTest.java
  src/test/java/com/dangdangsalon/domain/estimate/controller/EstimateControllerTest.java
Labels: 🎶 wontfix, 🚀 Refactor

#74 Feature: 콘테스트 결제내역 조회, 견적서 수정 시 수정 견적서 채팅으로 보내기 및 테스트 코드 작성
  src/main/java/com/dangdangsalon/domain/chat/service/ChatRoomService.java
  src/main/java/com/dangdangsalon/domain/contest/controller/ContestController.java
  src/main/java/com/dangdangsalon/domain/contest/dto/ContestPaymentDto.java
  src/main/java/com/dangdangsalon/domain/contest/dto/ContestPaymentRequestDto.java
  src/main/java/com/dangdangsalon/domain/estimate/request/repository/EstimateRequestServiceRepository.java
  src/main/java/com/dangdangsalon/domain/estimate/service/EstimateUpdateService.java
  src/main/java/com/dangdangsalon/domain/orders/repository/OrdersRepository.java
  src/main/java/com/dangdangsalon/domain/payment/service/PaymentGetService.java
  src/test/java/com/dangdangsalon/domain/contest/api/ContestApiTest.java
  src/test/java/com/dangdangsalon/domain/contest/controller/ContestControllerTest.java
  src/test/java/com/dangdangsalon/domain/estimate/request/repository/EstimateRequestServiceRepositoryTest.java
  src/test/java/com/dangdangsalon/domain/payment/service/PaymentGetServiceTest.java
Labels: help wanted, 📰 Test, ✨ Feat

#70 Feat: 콘테스트 게시글 올라올 때 구독자들에게 알림 기능 구현
  src/main/java/com/dangdangsalon/domain/contest/service/ContestPostService.java
  src/main/java/com/dangdangsalon/domain/contest/service/ContestTopicNotificationService.java
  src/test/java/com/dangdangsalon/domain/contest/service/ContestPostServiceTest.java
Labels: help wanted, ✨ Feat

#76 Feat: 지역 추천 미용사, 전국 인기 미용사 기능 구현
  src/main/java/com/dangdangsalon/domain/groomerprofile/repository/GroomerProfileRepository.java
  src/main/java/com/dangdangsalon/domain/groomerprofile/review/dto/ReviewUserResponseDto.java
  src/main/java/com/dangdangsalon/domain/mypage/controller/MyPageGroomerController.java
  src/main/java/com/dangdangsalon/domain/mypage/dto/res/GroomerMainResponseDto.java
  src/main/java/com/dangdangsalon/domain/mypage/dto/res/GroomerRecommendResponseDto.java
  src/main/java/com/dangdangsalon/domain/mypage/service/MyPageGroomerService.java
  src/test/java/com/dangdangsalon/domain/mypage/api/MyPageApiTest.java
  src/test/java/com/dangdangsalon/domain/mypage/controller/MyPageGroomerControllerTest.java
  src/test/java/com/dangdangsalon/domain/mypage/service/MyPageGroomerServiceTest.java
Labels: 🎶 wontfix, ✨ Feat

#77 Chore: 미용사 프로필 필수 등록 후 null 처리
  src/main/java/com/dangdangsalon/domain/mypage/dto/res/GroomerProfileDetailsResponseDto.java
  src/main/java/com/dangdangsalon/domain/mypage/service/MyPageGroomerService.java
Labels: 🎶 wontfix

#82 Refactor: checkLogin 에 알림 상태 값 추가
  src/main/java/com/dangdangsalon/domain/auth/dto/CheckLoginDto.java
  src/main/java/com/dangdangsalon/domain/auth/service/AuthService.java
  src/main/java/com/dangdangsalon/domain/auth/service/CustomOAuth2UserService.java
Labels: 🚀 Refactor

#83 Refactor: 이메일 알림 템플릿 적용
  src/main/java/com/dangdangsalon/domain/notification/service/NotificationEmailService.java
  src/main/java/com/dangdangsalon/domain/notification/service/NotificationScheduler.java
  src/main/resources/templates/email.html
  src/test/java/com/dangdangsalon/domain/notification/service/NotificationSchedulerTest.java
Labels: 🎶 wontfix, 🚀 Refactor

#84 Refactor: 푸시 알림 로직 리팩토링
  src/main/java/com/dangdangsalon/domain/estimate/request/service/GroomerEstimateRequestNotificationService.java
  src/main/java/com/dangdangsalon/domain/estimate/service/EstimateNotificationService.java
  src/main/java/com/dangdangsalon/domain/notification/service/NotificationService.java
  src/main/java/com/dangdangsalon/domain/payment/service/PaymentNotificationService.java
  src/test/java/com/dangdangsalon/domain/estimate/request/service/GroomerEstimateRequestNotificationServiceTest.java
  src/test/java/com/dangdangsalon/domain/estimate/service/EstimateNotificationServiceTest.java
  src/test/java/com/dangdangsalon/domain/payment/service/PaymentNotificationServiceTest.java
Labels: 🚀 Refactor

#90 Refactor: AuthService 수정
  src/main/java/com/dangdangsalon/domain/auth/service/AuthService.java
Labels: 🚀 Refactor

#91 Refactor: 결제 후 견적 요청 상태 PAID 로 변경 및 fcm 토큰 로직 수정
  src/main/java/com/dangdangsalon/domain/estimate/request/service/EstimateRequestServices.java
  src/main/java/com/dangdangsalon/domain/estimate/request/service/GroomerEstimateRequestNotificationService.java
  src/main/java/com/dangdangsalon/domain/estimate/service/EstimateNotificationService.java
  src/main/java/com/dangdangsalon/domain/notification/service/NotificationScheduler.java
  src/main/java/com/dangdangsalon/domain/notification/service/NotificationService.java
  src/main/java/com/dangdangsalon/domain/payment/service/PaymentNotificationService.java
  src/main/java/com/dangdangsalon/domain/payment/service/PaymentService.java
  src/test/java/com/dangdangsalon/domain/estimate/request/service/GroomerEstimateRequestNotificationServiceTest.java
  src/test/java/com/dangdangsalon/domain/estimate/service/EstimateNotificationServiceTest.java
  src/test/java/com/dangdangsalon/domain/notification/service/NotificationSchedulerTest.java
  src/test/java/com/dangdangsalon/domain/notification/service/NotificationServiceTest.java
  src/test/java/com/dangdangsalon/domain/payment/service/PaymentNotificationServiceTest.java
  src/test/java/com/dangdangsalon/domain/payment/service/PaymentServiceTest.java
Labels: 🚀 Refactor

#93 Refactor: 레포지토리 수정
  src/main/java/com/dangdangsalon/domain/notification/repository/FcmTokenRepository.java
  src/test/java/com/dangdangsalon/domain/notification/repository/FcmTokenRepositoryTest.java
Labels: 🚀 Refactor

#95 Refactor: 알림 setNotification -> putData 변경
  src/main/java/com/dangdangsalon/domain/notification/service/NotificationService.java
Labels: 🚀 Refactor

#96 알림 setNotification -> putData 변경
  src/main/java/com/dangdangsalon/domain/notification/service/NotificationService.java
Labels: 🚀 Refactor

#97 Refactor: 토픽 알림 setNotification -> putData 변경
  src/main/java/com/dangdangsalon/domain/notification/service/NotificationTopicService.java
Labels: 🚀 Refactor

#98 토픽 알림 setNotification -> putData 변경
  src/main/java/com/dangdangsalon/domain/notification/service/NotificationTopicService.java
Labels: 🚀 Refactor

#99 Refactor: 견적, 견적 요청, 결제 알림 비동기 처리
  src/main/java/com/dangdangsalon/domain/estimate/request/service/GroomerEstimateRequestNotificationService.java
  src/main/java/com/dangdangsalon/domain/estimate/service/EstimateNotificationService.java
  src/main/java/com/dangdangsalon/domain/notification/scheduler/NotificationScheduler.java
  src/main/java/com/dangdangsalon/domain/payment/service/PaymentNotificationService.java
  src/test/java/com/dangdangsalon/domain/notification/service/NotificationSchedulerTest.java
Labels: 🚀 Refactor

#100 알림 비동기 처리
  src/main/java/com/dangdangsalon/domain/estimate/request/service/GroomerEstimateRequestNotificationService.java
  src/main/java/com/dangdangsalon/domain/estimate/service/EstimateNotificationService.java
  src/main/java/com/dangdangsalon/domain/notification/scheduler/NotificationScheduler.java
  src/main/java/com/dangdangsalon/domain/payment/service/PaymentNotificationService.java
  src/test/java/com/dangdangsalon/domain/notification/service/NotificationSchedulerTest.java
Labels: 🚀 Refactor

#81 Feat: Gpt open ai 활용 강아지 미용 후 사진 생성
  src/main/java/com/dangdangsalon/chatgpt/controller/ChatGptController.java
  src/main/java/com/dangdangsalon/chatgpt/dto/ChatGPTMessage.java
  src/main/java/com/dangdangsalon/chatgpt/dto/ChoiceResponseDto.java
  src/main/java/com/dangdangsalon/chatgpt/dto/GenerateImageResponseDto.java
  src/main/java/com/dangdangsalon/chatgpt/dto/ImageDataResponseDto.java
  src/main/java/com/dangdangsalon/chatgpt/dto/ImageRequestDto.java
  src/main/java/com/dangdangsalon/chatgpt/dto/ImageResponseDto.java
  src/main/java/com/dangdangsalon/chatgpt/dto/MessageResponseDto.java
  src/main/java/com/dangdangsalon/chatgpt/dto/TranslateGptRequestDto.java
  src/main/java/com/dangdangsalon/chatgpt/dto/TranslateRequestDto.java
  src/main/java/com/dangdangsalon/chatgpt/dto/TranslateResponseDto.java
  src/main/java/com/dangdangsalon/chatgpt/service/ChatGptService.java
  src/main/java/com/dangdangsalon/config/ChatGptConfig.java
  src/main/java/com/dangdangsalon/config/MailConfig.java
Labels: 🎶 wontfix, ✨ Feat

#104 Refactor: ai 이미지 분석 결과 기능 추가
  src/main/java/com/dangdangsalon/chatgpt/controller/ChatGptController.java
  src/main/java/com/dangdangsalon/chatgpt/dto/GenerateImageAnalysisResponseDto.java
  src/main/java/com/dangdangsalon/chatgpt/service/ChatGptService.java
  src/test/java/com/dangdangsalon/chatgpt/api/ChatGptApiTest.java
  src/test/java/com/dangdangsalon/chatgpt/controller/ChatGptControllerTest.java
  src/test/java/com/dangdangsalon/chatgpt/service/ChatGptServiceTest.java
Labels: 🚀 Refactor

#106 Chore: 견적 요청 개수 가져올 때, PENDING -> COMPLETED 로 변경
  src/main/java/com/dangdangsalon/domain/mypage/service/MyPageGroomerService.java
Labels: 🎶 wontfix, 🚀 Refactor

#107 Ai 기능 추가 및 버그 수정
  src/main/java/com/dangdangsalon/chatgpt/controller/ChatGptController.java
  src/main/java/com/dangdangsalon/chatgpt/dto/ChatGPTMessage.java
  src/main/java/com/dangdangsalon/chatgpt/dto/ChoiceResponseDto.java
  src/main/java/com/dangdangsalon/chatgpt/dto/GenerateImageAnalysisResponseDto.java
  src/main/java/com/dangdangsalon/chatgpt/dto/ImageDataResponseDto.java
  src/main/java/com/dangdangsalon/chatgpt/dto/ImageRequestDto.java
  src/main/java/com/dangdangsalon/chatgpt/dto/ImageResponseDto.java
  src/main/java/com/dangdangsalon/chatgpt/dto/MessageResponseDto.java
  src/main/java/com/dangdangsalon/chatgpt/dto/TranslateGptRequestDto.java
  src/main/java/com/dangdangsalon/chatgpt/dto/TranslateRequestDto.java
  src/main/java/com/dangdangsalon/chatgpt/dto/TranslateResponseDto.java
  src/main/java/com/dangdangsalon/chatgpt/service/ChatGptService.java
  src/main/java/com/dangdangsalon/config/ChatGptConfig.java
  src/main/java/com/dangdangsalon/config/MailConfig.java
  src/main/java/com/dangdangsalon/domain/estimate/request/controller/EstimateRequestController.java
  src/main/java/com/dangdangsalon/domain/estimate/request/service/GroomerEstimateRequestService.java
  src/main/java/com/dangdangsalon/domain/groomerprofile/request/repository/GroomerEstimateRequestRepository.java
  src/main/java/com/dangdangsalon/domain/mypage/service/MyPageGroomerService.java
  src/main/resources/application-prod.properties
  src/test/java/com/dangdangsalon/chatgpt/api/ChatGptApiTest.java
  src/test/java/com/dangdangsalon/chatgpt/controller/ChatGptControllerTest.java
  src/test/java/com/dangdangsalon/chatgpt/service/ChatGptServiceTest.java
  src/test/java/com/dangdangsalon/domain/estimate/request/api/EstimateRequestApiTest.java
  src/test/java/com/dangdangsalon/domain/estimate/request/controller/EstimateRequestControllerTest.java
  src/test/java/com/dangdangsalon/domain/estimate/request/service/GroomerEstimateRequestServiceTest.java
  src/test/java/com/dangdangsalon/domain/notification/service/NotificationEmailServiceTest.java
  src/test/java/com/dangdangsalon/domain/notification/service/NotificationServiceTest.java
Labels: ✨ Feat

#109 Refactor: 강아지별 가격 수정
  src/main/java/com/dangdangsalon/domain/estimate/service/EstimateService.java
Labels: 🚀 Refactor

#108 Feat: 쿠폰 api 기능 구현
  src/main/java/com/dangdangsalon/config/RedisConfig.java
  src/main/java/com/dangdangsalon/config/RedisPublisher.java
  src/main/java/com/dangdangsalon/domain/coupon/controller/CouponController.java
  src/main/java/com/dangdangsalon/domain/coupon/controller/CouponEventController.java
  src/main/java/com/dangdangsalon/domain/coupon/controller/CouponTestController.java
  src/main/java/com/dangdangsalon/domain/coupon/dto/CouponInfoResponseDto.java
  src/main/java/com/dangdangsalon/domain/coupon/dto/CouponMainResponseDto.java
  src/main/java/com/dangdangsalon/domain/coupon/dto/CouponUserResponseDto.java
  src/main/java/com/dangdangsalon/domain/coupon/dto/QueueStatusDto.java
  src/main/java/com/dangdangsalon/domain/coupon/listener/RedisMessageSubscriber.java
  src/main/java/com/dangdangsalon/domain/coupon/repository/CouponEventRepository.java
  src/main/java/com/dangdangsalon/domain/coupon/repository/CouponRepository.java
  src/main/java/com/dangdangsalon/domain/coupon/scheduler/CouponScheduler.java
  src/main/java/com/dangdangsalon/domain/coupon/service/CouponIssueService.java
  src/main/java/com/dangdangsalon/domain/coupon/service/CouponService.java
  src/main/resources/static/coupon6.html
  src/main/resources/templates/coupontest.html
Labels: help wanted, ✨ Feat

#112 Chore: 유저 쿠폰 조회 시 NOT_USED 만 가져오게 수정
  src/main/java/com/dangdangsalon/domain/coupon/service/CouponService.java
Labels: 🎶 wontfix

#114 Refactor: 결제 승인, 취소 에러 메시지 추가 및 재시도 로직 추가
  build.gradle
  src/main/java/com/dangdangsalon/domain/payment/service/PaymentService.java
Labels: 🚀 Refactor

#115 견적 상태 값 추가 및 회원 탈퇴 외래키로 인한 V1, V10 수정
  src/main/java/com/dangdangsalon/domain/estimate/entity/EstimateStatus.java
  src/main/java/com/dangdangsalon/domain/payment/dto/PaymentResponseDto.java
  src/main/java/com/dangdangsalon/domain/payment/service/PaymentGetService.java
  src/main/java/com/dangdangsalon/domain/payment/service/PaymentService.java
  src/main/resources/db/migration/V10__update_constraints.sql
  src/main/resources/db/migration/V1__initial_schema.sql
  src/test/java/com/dangdangsalon/domain/payment/service/PaymentServiceTest.java
Labels: 🚀 Refactor

#116 Refactor: ai 강아지 종별 닮은 연예인 추가
  src/main/java/com/dangdangsalon/chatgpt/dto/DogCelebrityMapping.java
  src/main/java/com/dangdangsalon/chatgpt/dto/GenerateImageAnalysisResponseDto.java
  src/main/java/com/dangdangsalon/chatgpt/service/ChatGptService.java
  src/test/java/com/dangdangsalon/chatgpt/api/ChatGptApiTest.java
Labels: 🚀 Refactor

#117 Refactor: DogCelebrityMapping 수정
  src/main/java/com/dangdangsalon/chatgpt/DogCelebrityMapping.java
  src/main/java/com/dangdangsalon/chatgpt/service/ChatGptService.java
Labels: 🚀 Refactor

#118 Refactor: 이미지 분석 시 바로 한글 응답 오도록 수정
  src/main/java/com/dangdangsalon/chatgpt/dto/GenerateImageAnalysisResponseDto.java
  src/main/java/com/dangdangsalon/chatgpt/service/ChatGptService.java
Labels: 🚀 Refactor

#119 Refactor: 결제 내역 조회 응답 paymentKey 추가
  src/main/java/com/dangdangsalon/domain/payment/dto/PaymentResponseDto.java
  src/main/java/com/dangdangsalon/domain/payment/service/PaymentGetService.java
Labels: 🚀 Refactor

#120 견젹 요청 삭제 및 상태 변경 스케줄러 추가
  src/main/java/com/dangdangsalon/domain/estimate/request/repository/EstimateRequestRepository.java
  src/main/java/com/dangdangsalon/domain/estimate/request/scheduler/EstimateRequestStatusUpdateScheduler.java
  src/main/java/com/dangdangsalon/domain/estimate/request/scheduler/GroomerEstimateRequestCleanupScheduler.java
  src/main/java/com/dangdangsalon/domain/groomerprofile/request/repository/GroomerEstimateRequestRepository.java
Labels: ✨ Feat

#113 Test: 쿠폰 테스트 코드 작성
  src/test/java/com/dangdangsalon/domain/coupon/api/CouponApiTest.java
  src/test/java/com/dangdangsalon/domain/coupon/controller/CouponControllerTest.java
  src/test/java/com/dangdangsalon/domain/coupon/repository/CouponEventRepositoryTest.java
  src/test/java/com/dangdangsalon/domain/coupon/service/CouponIssueServiceTest.java
  src/test/java/com/dangdangsalon/domain/coupon/service/CouponSchedulerTest.java
  src/test/java/com/dangdangsalon/domain/coupon/service/CouponServiceTest.java
  src/test/java/com/dangdangsalon/domain/coupon/service/RedisMessageSubscriberTest.java
Labels: 📰 Test

#122 Refactor: 결제 승인 취소 서비스 분리
  src/main/java/com/dangdangsalon/domain/payment/service/PaymentApproveService.java
  src/main/java/com/dangdangsalon/domain/payment/service/PaymentCancelService.java
  src/main/java/com/dangdangsalon/domain/payment/service/PaymentService.java
  src/test/java/com/dangdangsalon/domain/estimate/request/service/EstimateRequestServicesTest.java
  src/test/java/com/dangdangsalon/domain/payment/service/PaymentApproveServiceTest.java
  src/test/java/com/dangdangsalon/domain/payment/service/PaymentCancelServiceTest.java
  src/test/java/com/dangdangsalon/domain/payment/service/PaymentServiceTest.java
Labels: 🚀 Refactor

#125 Refactor: 미용사 추천 정보 수정 및 프로필 전체 공개 페이지 설정
  src/main/java/com/dangdangsalon/domain/groomerprofile/repository/GroomerProfileRepository.java
  src/main/java/com/dangdangsalon/domain/mypage/dto/res/GroomerRecommendResponseDto.java
  src/main/java/com/dangdangsalon/domain/mypage/service/MyPageGroomerService.java
Labels: 🚀 Refactor

#126 Chore: 에러 메시지 수정
  src/main/java/com/dangdangsalon/domain/mypage/service/MyPageGroomerService.java
Labels: 🚀 Refactor

#127 Refactor : 변경사항 적용
  src/main/java/com/dangdangsalon/domain/chat/service/ChatRoomService.java
  src/main/java/com/dangdangsalon/domain/coupon/entity/Coupon.java
  src/main/java/com/dangdangsalon/domain/estimate/entity/EstimateStatus.java
  src/main/java/com/dangdangsalon/domain/estimate/repository/EstimateRepository.java
  src/main/java/com/dangdangsalon/domain/estimate/request/dto/EstimateDetailResponseDto.java
  src/main/java/com/dangdangsalon/domain/estimate/request/dto/EstimateRequestUserProfileResponseDto.java
  src/main/java/com/dangdangsalon/domain/estimate/request/dto/MyEstimateRequestResponseDto.java
  src/main/java/com/dangdangsalon/domain/estimate/request/entity/RequestStatus.java
  src/main/java/com/dangdangsalon/domain/estimate/request/service/EstimateRequestDetailService.java
  src/main/java/com/dangdangsalon/domain/estimate/request/service/EstimateRequestServices.java
  src/main/java/com/dangdangsalon/domain/estimate/request/service/GroomerEstimateRequestService.java
  src/main/java/com/dangdangsalon/domain/groomerprofile/repository/GroomerProfileRepository.java
  src/main/java/com/dangdangsalon/domain/groomerprofile/review/dto/ReviewUserResponseDto.java
  src/main/java/com/dangdangsalon/domain/mypage/dto/res/GroomerRecommendResponseDto.java
  src/main/java/com/dangdangsalon/domain/mypage/service/MyPageGroomerService.java
  src/main/java/com/dangdangsalon/domain/payment/dto/PaymentApproveRequestDto.java
  src/main/java/com/dangdangsalon/domain/payment/dto/PaymentCancelRequestDto.java
  src/main/java/com/dangdangsalon/domain/payment/dto/PaymentResponseDto.java
  src/main/java/com/dangdangsalon/domain/payment/entity/Payment.java
  src/main/java/com/dangdangsalon/domain/payment/service/PaymentApproveService.java
  src/main/java/com/dangdangsalon/domain/payment/service/PaymentCancelService.java
  src/main/java/com/dangdangsalon/domain/payment/service/PaymentGetService.java
  src/main/java/com/dangdangsalon/domain/payment/service/PaymentService.java
  src/main/resources/db/migration/V11__alter_payment_coupon.sql
  src/main/resources/db/migration/V1__initial_schema.sql
  src/test/java/com/dangdangsalon/domain/estimate/request/service/EstimateRequestDetailServiceTest.java
  src/test/java/com/dangdangsalon/domain/estimate/request/service/EstimateRequestServicesTest.java
  src/test/java/com/dangdangsalon/domain/payment/service/PaymentApproveServiceTest.java
  src/test/java/com/dangdangsalon/domain/payment/service/PaymentCancelServiceTest.java
  src/test/java/com/dangdangsalon/domain/payment/service/PaymentServiceTest.java
  src/test/java/com/dangdangsalon/domain/review/api/ReviewApiTest.java
  src/test/java/com/dangdangsalon/domain/review/controller/ReviewControllerTest.java
  src/test/java/com/dangdangsalon/domain/review/service/ReviewServiceTest.java
Labels: 🚀 Refactor

#128 스케줄러 테스트
  src/main/java/com/dangdangsalon/domain/notification/scheduler/NotificationScheduler.java
  src/main/java/com/dangdangsalon/domain/payment/service/PaymentCancelService.java
  src/test/java/com/dangdangsalon/domain/payment/service/PaymentCancelServiceTest.java
Labels: ✨ Feat

#129 fix: 테스트 코드 롤백
  src/test/java/com/dangdangsalon/domain/payment/service/PaymentCancelServiceTest.java
Labels: 🛠️ Fix

#131 Refactor: 이메일 알림 로직 수정
  src/main/java/com/dangdangsalon/domain/contest/service/ContestPostLikeService.java
  src/main/java/com/dangdangsalon/domain/notification/scheduler/NotificationScheduler.java
  src/main/java/com/dangdangsalon/domain/payment/repository/PaymentRepository.java
  src/main/java/com/dangdangsalon/domain/payment/service/PaymentApproveService.java
  src/main/java/com/dangdangsalon/domain/payment/service/PaymentCancelService.java
  src/test/java/com/dangdangsalon/domain/notification/service/NotificationSchedulerTest.java
Labels: 🚀 Refactor

#132 Develop
  src/main/java/com/dangdangsalon/domain/contest/service/ContestPostLikeService.java
  src/main/java/com/dangdangsalon/domain/notification/scheduler/NotificationScheduler.java
  src/main/java/com/dangdangsalon/domain/orders/repository/OrdersRepository.java
  src/main/java/com/dangdangsalon/domain/payment/repository/PaymentRepository.java
  src/main/java/com/dangdangsalon/domain/payment/service/PaymentApproveService.java
  src/main/java/com/dangdangsalon/domain/payment/service/PaymentCancelService.java
  src/main/java/com/dangdangsalon/domain/payment/service/PaymentGetService.java
  src/test/java/com/dangdangsalon/domain/notification/service/NotificationSchedulerTest.java
  src/test/java/com/dangdangsalon/domain/orders/repository/OrdersRepositoryTest.java
  src/test/java/com/dangdangsalon/domain/payment/service/PaymentGetServiceTest.java
Labels: 🚀 Refactor

#133 Refactor: 내 견적 요청 조회 로직 수정
  src/main/java/com/dangdangsalon/domain/estimate/repository/EstimateRepository.java
  src/main/java/com/dangdangsalon/domain/estimate/request/service/EstimateRequestServices.java
Labels: 🚀 Refactor

#134 Refactor: 결제 승인 취소 재시도 클래스 분리
  build.gradle
  src/main/java/com/dangdangsalon/DangdangSalonServerApplication.java
  src/main/java/com/dangdangsalon/domain/payment/service/PaymentApproveRetryService.java
  src/main/java/com/dangdangsalon/domain/payment/service/PaymentApproveService.java
  src/main/java/com/dangdangsalon/domain/payment/service/PaymentCancelRetryService.java
  src/main/java/com/dangdangsalon/domain/payment/service/PaymentCancelService.java
  src/test/java/com/dangdangsalon/domain/payment/service/PaymentApproveRetryServiceTest.java
  src/test/java/com/dangdangsalon/domain/payment/service/PaymentApproveServiceTest.java
  src/test/java/com/dangdangsalon/domain/payment/service/PaymentCancelRetryServiceTest.java
  src/test/java/com/dangdangsalon/domain/payment/service/PaymentCancelServiceTest.java
Labels: 🚀 Refactor

#135 결제 승인 취소 재시도 클래스 분리
  build.gradle
  src/main/java/com/dangdangsalon/DangdangSalonServerApplication.java
  src/main/java/com/dangdangsalon/domain/payment/service/PaymentApproveRetryService.java
  src/main/java/com/dangdangsalon/domain/payment/service/PaymentApproveService.java
  src/main/java/com/dangdangsalon/domain/payment/service/PaymentCancelRetryService.java
  src/main/java/com/dangdangsalon/domain/payment/service/PaymentCancelService.java
  src/test/java/com/dangdangsalon/domain/payment/service/PaymentApproveRetryServiceTest.java
  src/test/java/com/dangdangsalon/domain/payment/service/PaymentApproveServiceTest.java
  src/test/java/com/dangdangsalon/domain/payment/service/PaymentCancelRetryServiceTest.java
  src/test/java/com/dangdangsalon/domain/payment/service/PaymentCancelServiceTest.java
Labels: 🚀 Refactor

#136 Refactor: 결제 내역 조회 수정 및 유저 cascade 조건 변경
  src/main/java/com/dangdangsalon/domain/mypage/service/MyPageDogProfileService.java
  src/main/java/com/dangdangsalon/domain/mypage/service/MyPageGroomerService.java
  src/main/java/com/dangdangsalon/domain/orders/repository/OrdersRepository.java
  src/main/java/com/dangdangsalon/domain/user/entity/User.java
  src/test/java/com/dangdangsalon/domain/mypage/service/MyPageGroomerServiceTest.java
Labels: 🚀 Refactor

#137 구독 알림 기능 리팩토링
  src/main/java/com/dangdangsalon/domain/notification/controller/NotificationController.java
  src/main/java/com/dangdangsalon/domain/notification/entity/Topic.java
  src/main/java/com/dangdangsalon/domain/notification/repository/TopicRepository.java
  src/main/java/com/dangdangsalon/domain/notification/service/NotificationTopicService.java
  src/main/resources/db/migration/V12__alter_table_topic.sql
  src/test/java/com/dangdangsalon/domain/notification/api/NotificationApiTest.java
  src/test/java/com/dangdangsalon/domain/notification/controller/NotificationControllerTest.java
  src/test/java/com/dangdangsalon/domain/notification/service/NotificationTopicServiceTest.java
Labels: 🚀 Refactor

#138 구독 알림 기능 리팩토링
  src/main/java/com/dangdangsalon/domain/mypage/service/MyPageDogProfileService.java
  src/main/java/com/dangdangsalon/domain/mypage/service/MyPageGroomerService.java
  src/main/java/com/dangdangsalon/domain/notification/controller/NotificationController.java
  src/main/java/com/dangdangsalon/domain/notification/entity/Topic.java
  src/main/java/com/dangdangsalon/domain/notification/repository/TopicRepository.java
  src/main/java/com/dangdangsalon/domain/notification/service/NotificationTopicService.java
  src/main/java/com/dangdangsalon/domain/orders/repository/OrdersRepository.java
  src/main/java/com/dangdangsalon/domain/user/entity/User.java
  src/main/resources/db/migration/V12__alter_table_topic.sql
  src/test/java/com/dangdangsalon/domain/mypage/service/MyPageGroomerServiceTest.java
  src/test/java/com/dangdangsalon/domain/notification/api/NotificationApiTest.java
  src/test/java/com/dangdangsalon/domain/notification/controller/NotificationControllerTest.java
  src/test/java/com/dangdangsalon/domain/notification/service/NotificationTopicServiceTest.java
Labels: 🚀 Refactor

#139 Refactor: 결제 알림 미용사한테 가도록 수정
  src/main/java/com/dangdangsalon/domain/payment/service/PaymentNotificationService.java
  src/test/java/com/dangdangsalon/domain/payment/service/PaymentNotificationServiceTest.java
Labels: 🚀 Refactor

#66 Test: 채팅 API 테스트 코드 작성
  build.gradle
  src/main/java/com/dangdangsalon/domain/chat/entity/ChatRoom.java
  src/main/java/com/dangdangsalon/domain/user/entity/User.java
  src/test/java/com/dangdangsalon/domain/chat/api/ChatApiTest.java
  src/test/java/com/dangdangsalon/domain/chat/controller/ChatRoomControllerTest.java
  src/test/java/com/dangdangsalon/domain/chat/repository/ChatMessageRepositoryTest.java
  src/test/java/com/dangdangsalon/domain/chat/repository/ChatRoomRepositoryTest.java
  src/test/java/com/dangdangsalon/domain/chat/service/ChatMessageMongoServiceTest.java
  src/test/java/com/dangdangsalon/domain/chat/service/ChatMessageServiceTest.java
  src/test/java/com/dangdangsalon/domain/chat/service/ChatRoomServiceTest.java
  src/test/java/com/dangdangsalon/domain/chat/service/ChatServiceTest.java
Labels: 📰 Test

#85 Feat: 이벤트 1시간 전 알림 기능 구현(kafka)
  src/main/java/com/dangdangsalon/config/KafkaConsumerConfig.java
  src/main/java/com/dangdangsalon/config/KafkaProducerConfig.java
  src/main/java/com/dangdangsalon/config/KafkaTopicConfig.java
  src/main/java/com/dangdangsalon/domain/coupon/repository/CouponEventRepository.java
  src/main/java/com/dangdangsalon/domain/coupon/service/CouponKafkaNotificationService.java
  src/main/java/com/dangdangsalon/domain/notification/dto/EventNotificationDto.java
  src/main/java/com/dangdangsalon/domain/notification/service/EventNotificationConsumer.java
  src/main/java/com/dangdangsalon/domain/notification/service/EventNotificationProducer.java
Labels: ✨ Feat, 🚀 Refactor

#111 Test: 카프카 알림 추가 테스트 코드 작성
  src/main/java/com/dangdangsalon/config/KafkaTopicConfig.java
  src/main/java/com/dangdangsalon/domain/coupon/repository/CouponEventRepository.java
  src/test/java/com/dangdangsalon/domain/coupon/service/CouponKafkaNotificationServiceTest.java
  src/test/java/com/dangdangsalon/domain/notification/service/EventNotificationConsumerTest.java
  src/test/java/com/dangdangsalon/domain/notification/service/EventNotificationProducerTest.java
Labels: 📰 Test

#141 이벤트 알림 조회 시간 수정
  src/main/java/com/dangdangsalon/domain/coupon/service/CouponKafkaNotificationService.java
  src/test/java/com/dangdangsalon/domain/coupon/service/CouponKafkaNotificationServiceTest.java
Labels: 🚀 Refactor

#143 Refactor: 동적 스케줄러 적용
  src/main/java/com/dangdangsalon/config/SchedulerConfig.java
  src/main/java/com/dangdangsalon/domain/coupon/controller/CouponEventController.java
  src/main/java/com/dangdangsalon/domain/coupon/dto/CouponMainResponseDto.java
  src/main/java/com/dangdangsalon/domain/coupon/repository/CouponEventRepository.java
  src/main/java/com/dangdangsalon/domain/coupon/scheduler/CouponScheduler.java
  src/main/java/com/dangdangsalon/domain/coupon/scheduler/EventInitializer.java
  src/main/java/com/dangdangsalon/domain/coupon/service/CouponEventService.java
  src/main/java/com/dangdangsalon/domain/coupon/service/CouponIssueService.java
  src/main/java/com/dangdangsalon/domain/coupon/service/CouponService.java
  src/test/java/com/dangdangsalon/domain/coupon/scheduler/CouponSchedulerTest.java
  src/test/java/com/dangdangsalon/domain/coupon/service/CouponSchedulerTest.java
  src/test/java/com/dangdangsalon/domain/coupon/service/CouponServiceTest.java
Labels: 🚀 Refactor

#145 Refactor: 미용사 닉네임 중복 확인
  src/main/java/com/dangdangsalon/domain/groomerprofile/repository/GroomerProfileRepository.java
  src/main/java/com/dangdangsalon/domain/mypage/controller/MyPageGroomerController.java
  src/main/java/com/dangdangsalon/domain/mypage/service/MyPageGroomerService.java
  src/test/java/com/dangdangsalon/domain/mypage/api/MyPageApiTest.java
  src/test/java/com/dangdangsalon/domain/mypage/controller/MyPageGroomerControllerTest.java
  src/test/java/com/dangdangsalon/domain/mypage/service/MyPageGroomerServiceTest.java
Labels: 🚀 Refactor
